### ISSUE TITLE
`koumura2annot` throws an error when annot_file is a Path not a str

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/crowsetta#51]
```
Traceback (most recent call last):
  File "/home/art/anaconda3/envs/vak-dev/bin/vak", line 11, in <module>
    load_entry_point('vak', 'console_scripts', 'vak')()
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/__main__.py", line 43, in main
    config_file=args.configfile)
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/cli/cli.py", line 18, in cli
    prep(toml_path=config_file)
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/cli/prep.py", line 162, in prep
    logger=logger)
  File "/home/art/Documents/repos/coding/birdsong/vak/src/vak/io/dataframe.py", line 124, in from_files
    annot_list = scribe.from_file(annot_file=annot_file)
  File "/home/art/anaconda3/envs/vak-dev/lib/python3.6/site-packages/crowsetta/koumura.py", line 53, in koumura2annot
    if not annot_file.endswith('.xml'):
AttributeError: 'PosixPath' object has no attribute 'endswith'
```

**Comment by NickleDave** [comment]
fixed by #53
